apiVersion: forward.webhookrelay.com/v1
kind: WebhookRelayForward
metadata:
  name: keel-forward
spec:
  buckets:
  - name: dockerhub-to-keel
    inputs:
    - name: dockerhub-endpoint
      description: "Public endpoint"
      responseBody: "OK"
      responseStatusCode: 200
    outputs:
    - name: keel
      destination: http://keel:9300/v1/webhooks/dockerhub
      internal: true
  # - name: dockerhub-to-keel2
  #   inputs:
  #   - name: dockerhub-endpoint2
  #     description: "Public endpoint2"
  #     responseBody: "OK"
  #     responseStatusCode: 200
  #   outputs:
  #   - name: keel2
  #     destination: http://localhost:123/teste
  #     internal: true