apiVersion: v1
kind: Service
metadata: 
  name: api-service
  namespace: crud-with-node
spec:
  selector:
    app: api-node-pod-label
  ports:
    - name: http
      port: 3000
      nodePort: 30080
  type: NodePort