apiVersion: v1
kind: Service
metadata:
  name: mongo
  # namespace: crud-with-node
spec:
  selector:
    app: mongodb-pod-label
  ports:
    - name: http
      port: 27017
      nodePort: 30081
  type: NodePort